import { useState } from 'react'
import { Card, Select, Button, Space, Typography, message } from 'antd'
import { DownloadOutlined } from '@ant-design/icons'
import { useTranslation } from 'react-i18next'
import { useSchoolStore } from '../../store/schoolStore'
import dayjs from 'dayjs'

const { Title, Text } = Typography

export default function ExportPanel() {
  const { t } = useTranslation()
  const { school: storeSchool } = useSchoolStore()
  const [exportType, setExportType] = useState('students')
  const [loading, setLoading] = useState(false)

  const handleExport = async () => {
    if (!storeSchool) return
    setLoading(true)
    try {
      const ExcelJS = await import('exceljs')
      const school = await window.api.app.getSchool()
      if (exportType === 'students') await exportStudents(ExcelJS, school)
      else if (exportType === 'attendance') await exportAttendance(ExcelJS, school)
      else if (exportType === 'marks') await exportMarks(ExcelJS, school)
      message.success(t('common.success'))
    } catch (e: any) { message.error(e?.message || t('errors.generic')) }
    finally { setLoading(false) }
  }

  function styleHeader(ws: any, row: number, cols: number) {
    for (let c = 1; c <= cols; c++) {
      const cell = ws.getRow(row).getCell(c)
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE8EAFF' } }
      cell.font = { name: 'Calibri', bold: true, size: 11, color: { argb: 'FF1E3A5F' } }
      cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true }
      cell.border = { top: { style: 'thin' }, bottom: { style: 'thin' }, left: { style: 'thin' }, right: { style: 'thin' } }
    }
    ws.getRow(row).height = 22
  }

  function styleDataRow(ws: any, row: number, cols: number, isEven: boolean, centerCols: Set<number>) {
    for (let c = 1; c <= cols; c++) {
      const cell = ws.getRow(row).getCell(c)
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: isEven ? 'FFFFFFFF' : 'FFEEF2FF' } }
      cell.font = { name: 'Calibri', size: 10, color: { argb: 'FF333333' } }
      cell.border = { top: { style: 'thin' }, bottom: { style: 'thin' }, left: { style: 'thin' }, right: { style: 'thin' } }
      cell.alignment = { horizontal: centerCols.has(c) ? 'center' : 'left', vertical: 'middle' }
    }
    ws.getRow(row).height = 18
  }

  function addSheetHeaders(ws: any, school: any, cols: number) {
    ws.mergeCells(1, 1, 1, cols)
    const r1 = ws.getCell('A1'); r1.value = school?.name || ''
    r1.font = { name: 'Calibri', bold: true, size: 18, color: { argb: 'FF8B0000' } }
    r1.alignment = { horizontal: 'center', vertical: 'middle' }; ws.getRow(1).height = 35

    const addr = [school?.address, school?.principal_name].filter(Boolean).join(' | ')
    if (addr) {
      ws.mergeCells(2, 1, 2, cols)
      const r2 = ws.getCell('A2'); r2.value = addr
      r2.font = { name: 'Calibri', size: 11, color: { argb: 'FF555555' } }; r2.alignment = { horizontal: 'center', vertical: 'middle' }
    }

    ws.mergeCells(3, 1, 3, cols)
    const r3 = ws.getCell('A3'); r3.value = `Exported: ${dayjs().format('DD/MM/YYYY')}`
    r3.font = { name: 'Calibri', size: 10, color: { argb: 'FF555555' } }; r3.alignment = { horizontal: 'center', vertical: 'middle' }
  }

  function addFooter(ws: any, row: number, cols: number, count: number) {
    ws.mergeCells(row, 1, row, cols)
    const f = ws.getCell(row, 1); f.value = `${count} students | Generated by Darj | ${dayjs().format('DD/MM/YYYY HH:mm')}`
    f.font = { name: 'Calibri', italic: true, size: 9, color: { argb: 'FF888888' } }; f.alignment = { horizontal: 'right' }
  }

  async function exportStudents(ExcelJS: any, school: any) {
    const fields = await window.api.fields.get(school.id)
    const sections = await window.api.sections.getAll(school.id)
    const wb = new ExcelJS.Workbook()
    const headers = ['Class', 'Section', ...fields.map((f: any) => f.display_name), 'Status']
    const cols = headers.length
    const centerCols = new Set<number>([1, 2, headers.length]) // Class, Section, Status

    for (const sec of sections) {
      const students = await window.api.students.getBySection(sec.id)
      if (students.length === 0) continue
      const ws = wb.addWorksheet(`${sec.class_name || 'Class'} ${sec.name}`.substring(0, 31))
      addSheetHeaders(ws, school, cols)
      headers.forEach((h, i) => { ws.getCell(5, i + 1).value = h })
      styleHeader(ws, 5, cols)

      students.forEach((s: any, ri: number) => {
        const row = 6 + ri
        ws.getCell(row, 1).value = sec.class_name || ''; ws.getCell(row, 2).value = sec.name || ''
        fields.forEach((f: any, fi: number) => {
          const v = s.field_values?.[f.field_key]
          if (v === null || v === undefined || v === '') { ws.getCell(row, 3 + fi).value = ''; return }
          if (f.field_type === 'date') { const d = dayjs(v); ws.getCell(row, 3 + fi).value = d.isValid() ? d.format('DD/MM/YYYY') : v; return }
          if (f.field_type === 'number') { ws.getCell(row, 3 + fi).value = Number(v); return }
          ws.getCell(row, 3 + fi).value = String(v)
        })
        ws.getCell(row, cols).value = s.status
        styleDataRow(ws, row, cols, ri % 2 === 0, centerCols)
      })
      addFooter(ws, 6 + students.length, cols, students.length)
      ws.columns = headers.map((h, i) => {
        const w = i === 0 ? 10 : i === 1 ? 10 : h === 'Full Name' ? 25 : h === "Father's Name" ? 22 : h === "Mother's Name" ? 22 : h === 'Address' ? 30 : Math.min(20, Math.max(10, h.length + 4))
        return { width: w }
      })
    }
    const buf = await wb.xlsx.writeBuffer()
    saveBlob(buf, `Students_${school?.name || 'Export'}.xlsx`)
  }

  async function exportAttendance(ExcelJS: any, school: any) {
    const sections = await window.api.sections.getAll(school.id)
    const wb = new ExcelJS.Workbook()
    const startDate = new Date(); startDate.setMonth(startDate.getMonth() - 1)
    const endDate = new Date()
    const fmt = (d: Date) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`

    for (const sec of sections) {
      const students = await window.api.students.getBySection(sec.id)
      if (students.length === 0) continue
      const dates: string[] = []
      for (let d = new Date(startDate); d <= endDate; d.setDate(d.getDate()+1)) dates.push(fmt(d))
      const headers = ['Name', ...dates, 'Present', 'Absent', 'Attendance %']
      const cols = headers.length
      const ws = wb.addWorksheet(`Att ${sec.class_name} ${sec.name}`.substring(0, 31))
      addSheetHeaders(ws, school, cols)
      headers.forEach((h, i) => { ws.getCell(5, i + 1).value = h })
      styleHeader(ws, 5, cols)

      for (let ri = 0; ri < students.length; ri++) {
        const s = students[ri]
        const attRecords = await window.api.attendance.getByStudent(s.id, fmt(startDate), fmt(endDate))
        const am: Record<string, string> = {}; attRecords.forEach((r: any) => { am[r.date] = r.status })
        ws.getCell(6 + ri, 1).value = s.field_values?.full_name || ''
        let p = 0
        dates.forEach((d, di) => {
          const val = am[d] ? am[d][0].toUpperCase() : ''
          ws.getCell(6 + ri, 2 + di).value = val; if (val === 'P') p++
          ws.getCell(6 + ri, 2 + di).alignment = { horizontal: 'center', vertical: 'middle' }
        })
        const pct = dates.length > 0 ? Math.round((p / dates.length) * 100) : 0
        ws.getCell(6 + ri, 2 + dates.length).value = p
        ws.getCell(6 + ri, 3 + dates.length).value = dates.length - p
        ws.getCell(6 + ri, 4 + dates.length).value = `${pct}%`
        styleDataRow(ws, 6 + ri, cols, ri % 2 === 0, new Set())
      }
      addFooter(ws, 6 + students.length, cols, students.length)
      ws.columns = headers.map((h) => ({ width: Math.max(10, h.length + 2) }))
    }
    const buf = await wb.xlsx.writeBuffer()
    saveBlob(buf, `Attendance_${school?.name || 'Export'}.xlsx`)
  }

  async function exportMarks(ExcelJS: any, school: any) {
    const classes = await window.api.classes.get(school.id)
    const wb = new ExcelJS.Workbook()

    for (const cls of classes) {
      const sections = await window.api.sections.getByClass(cls.id)
      const subjects = await window.api.marks.getSubjects(cls.id)
      for (const sec of sections) {
        const students = await window.api.students.getBySection(sec.id)
        if (students.length === 0) continue
        const headers = ['Name', ...subjects.map((s: any) => s.name), 'Result', 'Percentage']
        const cols = headers.length
        const ws = wb.addWorksheet(`Marks ${cls.name} ${sec.name}`.substring(0, 31))
        addSheetHeaders(ws, school, cols)
        headers.forEach((h, i) => { ws.getCell(5, i + 1).value = h })
        styleHeader(ws, 5, cols)

        for (let ri = 0; ri < students.length; ri++) {
          const st = students[ri]
          const marks = await window.api.marks.getByStudent(st.id)
          ws.getCell(6 + ri, 1).value = st.field_values?.full_name || ''
          let totO = 0, allPassed = subjects.length > 0
          for (let si = 0; si < subjects.length; si++) {
            const sub = subjects[si]
            const sm = marks.filter((m: any) => m.subject_id === sub.id)
            const avg = sm.length > 0 ? Math.round(sm.reduce((a: number, m: any) => a + (m.marks_obtained||0), 0) / sm.length) : 0
            ws.getCell(6 + ri, 2 + si).value = avg > 0 ? `${avg}/${sm[0]?.max_marks || 100}` : ''
            totO += avg
            if (sm.length > 0 && sm.some((m: any) => m.is_pass === 0)) allPassed = false
          }
          const pct = subjects.length > 0 ? Math.round(totO / subjects.length) : 0
          ws.getCell(6 + ri, 1 + subjects.length + 1).value = subjects.length === 0 ? '' : allPassed ? 'Pass' : 'Fail'
          ws.getCell(6 + ri, 1 + subjects.length + 2).value = pct > 0 ? `${pct}%` : ''
          styleDataRow(ws, 6 + ri, cols, ri % 2 === 0, new Set())
        }
        addFooter(ws, 6 + students.length, cols, students.length)
        ws.columns = headers.map((h) => ({ width: Math.max(10, h.length + 2) }))
      }
    }
    const buf = await wb.xlsx.writeBuffer()
    saveBlob(buf, `Marks_${school?.name || 'Export'}.xlsx`)
  }

  function saveBlob(buffer: ArrayBuffer, filename: string) {
    const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })
    const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = filename; a.click()
  }

  return (
    <div>
      <Title level={4}>{t('sidebar.export')}</Title>
      <Card style={{ maxWidth: 400, borderTop: '3px solid #2A6372' }}>
        <Space direction="vertical" style={{ width: '100%' }}>
          <Text>Export data as professionally formatted Excel (.xlsx)</Text>
          <Select value={exportType} onChange={setExportType} options={[
            { value: 'students', label: 'Students' },
            { value: 'attendance', label: 'Attendance' },
            { value: 'marks', label: 'Marks' }
          ]} />
          <Button type="primary" icon={<DownloadOutlined />} onClick={handleExport} loading={loading} block>
            Export to Excel
          </Button>
        </Space>
      </Card>
    </div>
  )
}
